/*
 * Fincura Integration API
 * This [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) allows you to interact with the Fincura processing and insights engine.   # Authentication  This API uses API keys generated from a Fincura User account. To get access to your User account, speak with you Fincura account manager.  # Accepted Media Types  | File&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Extension(s)     | Content-Type(s) | | -------------------------------- |-------------- | ------------ | | PDF File | .pdf | `application/pdf` , `application/x-pdf` | | Excel File | .xls | `application/vnd.ms-excel`  | | Excel File | .xlsx | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`  | | PNG Image | .png | `image/png`  | | GIF Image | .gif | `image/gif`  | | JPG Image | .jpg, .jpeg | `image/jpeg`  | | GIF Image | .gif | `image/gif`  |   # Getting Started  1. [Create a Borrower](#operation/createBorrower)  2. [Add a file](#operation/createDocumentFile) for that Borrower. 3. Analyze in the Fincura App  ****
 *
 * The version of the OpenAPI document: 1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fincura.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.fincura.client.model.LoanBorrowerInfo;
import org.fincura.client.model.LoanComplianceInfo;
import org.fincura.client.model.LoanDocuments;
import org.fincura.client.model.LoanFinancials;
import org.fincura.client.model.LoanGuarantors;
import org.fincura.client.model.LoanPeriods;
import org.fincura.client.model.LoanPriorYearFinancials;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Loan
 */
public class LoanTest {
    private final Loan model = new Loan();

    /**
     * Model tests for Loan
     */
    @Test
    public void testLoan() {
        // TODO: test Loan
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'loanId'
     */
    @Test
    public void loanIdTest() {
        // TODO: test loanId
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'borrowerUuid'
     */
    @Test
    public void borrowerUuidTest() {
        // TODO: test borrowerUuid
    }

    /**
     * Test the property 'borrowerInfo'
     */
    @Test
    public void borrowerInfoTest() {
        // TODO: test borrowerInfo
    }

    /**
     * Test the property 'principal'
     */
    @Test
    public void principalTest() {
        // TODO: test principal
    }

    /**
     * Test the property 'interestRate'
     */
    @Test
    public void interestRateTest() {
        // TODO: test interestRate
    }

    /**
     * Test the property 'interestType'
     */
    @Test
    public void interestTypeTest() {
        // TODO: test interestType
    }

    /**
     * Test the property 'termMonths'
     */
    @Test
    public void termMonthsTest() {
        // TODO: test termMonths
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'paymentStatus'
     */
    @Test
    public void paymentStatusTest() {
        // TODO: test paymentStatus
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'monthlyPayment'
     */
    @Test
    public void monthlyPaymentTest() {
        // TODO: test monthlyPayment
    }

    /**
     * Test the property 'paymentsRemaining'
     */
    @Test
    public void paymentsRemainingTest() {
        // TODO: test paymentsRemaining
    }

    /**
     * Test the property 'outstandingPrincipal'
     */
    @Test
    public void outstandingPrincipalTest() {
        // TODO: test outstandingPrincipal
    }

    /**
     * Test the property 'interestAccrued'
     */
    @Test
    public void interestAccruedTest() {
        // TODO: test interestAccrued
    }

    /**
     * Test the property 'loanToValue'
     */
    @Test
    public void loanToValueTest() {
        // TODO: test loanToValue
    }

    /**
     * Test the property 'scorecard'
     */
    @Test
    public void scorecardTest() {
        // TODO: test scorecard
    }

    /**
     * Test the property 'collateralType'
     */
    @Test
    public void collateralTypeTest() {
        // TODO: test collateralType
    }

    /**
     * Test the property 'collateralValue'
     */
    @Test
    public void collateralValueTest() {
        // TODO: test collateralValue
    }

    /**
     * Test the property 'collateralLifeMonths'
     */
    @Test
    public void collateralLifeMonthsTest() {
        // TODO: test collateralLifeMonths
    }

    /**
     * Test the property 'residualValue'
     */
    @Test
    public void residualValueTest() {
        // TODO: test residualValue
    }

    /**
     * Test the property 'balloonPayment'
     */
    @Test
    public void balloonPaymentTest() {
        // TODO: test balloonPayment
    }

    /**
     * Test the property 'lastPaymentDate'
     */
    @Test
    public void lastPaymentDateTest() {
        // TODO: test lastPaymentDate
    }

    /**
     * Test the property 'complianceInfo'
     */
    @Test
    public void complianceInfoTest() {
        // TODO: test complianceInfo
    }

    /**
     * Test the property 'templateUuid'
     */
    @Test
    public void templateUuidTest() {
        // TODO: test templateUuid
    }

    /**
     * Test the property 'periods'
     */
    @Test
    public void periodsTest() {
        // TODO: test periods
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'financials'
     */
    @Test
    public void financialsTest() {
        // TODO: test financials
    }

    /**
     * Test the property 'analysisCommentary'
     */
    @Test
    public void analysisCommentaryTest() {
        // TODO: test analysisCommentary
    }

    /**
     * Test the property 'guarantors'
     */
    @Test
    public void guarantorsTest() {
        // TODO: test guarantors
    }

    /**
     * Test the property 'priorYearFinancials'
     */
    @Test
    public void priorYearFinancialsTest() {
        // TODO: test priorYearFinancials
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

}
