/*
 * Fincura API
 * This [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) allows you to interact with the Fincura processing and insights engine.   # Authentication  This API uses API keys generated from a Fincura User account. To get access to your User account, speak with you Fincura account manager.  # Accepted Media Types  | File&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Extension(s)     | Content-Type(s) | | -------------------------------- |-------------- | ------------ | | PDF File | .pdf | `application/pdf` , `application/x-pdf` | | Excel File | .xls | `application/vnd.ms-excel`  | | Excel File | .xlsx | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`  | | Excel File | .xlsm | `application/vnd.ms-excel.sheet.macroEnabled.12`  | | PNG Image | .png | `image/png`  | | GIF Image | .gif | `image/gif`  | | JPG Image | .jpg, .jpeg | `image/jpeg`  | | GIF Image | .gif | `image/gif`  |   # Getting Started  1. [Create a Borrower](#operation/createBorrower)  2. [Add a file](#operation/createDocumentFile) for that Borrower. 3. Analyze in the Fincura App  ****
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@fincura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fincura.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Compliance information for this loan and borrower
 */
@ApiModel(description = "Compliance information for this loan and borrower")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-27T00:03:41.356Z[GMT]")
public class LoanComplianceInfo {
  public static final String SERIALIZED_NAME_OFAC_SANCTIONS = "ofac_sanctions";
  @SerializedName(SERIALIZED_NAME_OFAC_SANCTIONS)
  private Boolean ofacSanctions;

  public static final String SERIALIZED_NAME_PACER_BANKRUPTCIES = "pacer_bankruptcies";
  @SerializedName(SERIALIZED_NAME_PACER_BANKRUPTCIES)
  private Boolean pacerBankruptcies;

  public static final String SERIALIZED_NAME_STATE_COURT_CLAIMS = "state_court_claims";
  @SerializedName(SERIALIZED_NAME_STATE_COURT_CLAIMS)
  private Boolean stateCourtClaims;

  public static final String SERIALIZED_NAME_DIVISIONS_OF_CORP_REPORT = "divisions_of_corp_report";
  @SerializedName(SERIALIZED_NAME_DIVISIONS_OF_CORP_REPORT)
  private Boolean divisionsOfCorpReport;


  public LoanComplianceInfo ofacSanctions(Boolean ofacSanctions) {
    
    this.ofacSanctions = ofacSanctions;
    return this;
  }

   /**
   * Get ofacSanctions
   * @return ofacSanctions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOfacSanctions() {
    return ofacSanctions;
  }


  public void setOfacSanctions(Boolean ofacSanctions) {
    this.ofacSanctions = ofacSanctions;
  }


  public LoanComplianceInfo pacerBankruptcies(Boolean pacerBankruptcies) {
    
    this.pacerBankruptcies = pacerBankruptcies;
    return this;
  }

   /**
   * Get pacerBankruptcies
   * @return pacerBankruptcies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getPacerBankruptcies() {
    return pacerBankruptcies;
  }


  public void setPacerBankruptcies(Boolean pacerBankruptcies) {
    this.pacerBankruptcies = pacerBankruptcies;
  }


  public LoanComplianceInfo stateCourtClaims(Boolean stateCourtClaims) {
    
    this.stateCourtClaims = stateCourtClaims;
    return this;
  }

   /**
   * Get stateCourtClaims
   * @return stateCourtClaims
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getStateCourtClaims() {
    return stateCourtClaims;
  }


  public void setStateCourtClaims(Boolean stateCourtClaims) {
    this.stateCourtClaims = stateCourtClaims;
  }


  public LoanComplianceInfo divisionsOfCorpReport(Boolean divisionsOfCorpReport) {
    
    this.divisionsOfCorpReport = divisionsOfCorpReport;
    return this;
  }

   /**
   * Get divisionsOfCorpReport
   * @return divisionsOfCorpReport
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDivisionsOfCorpReport() {
    return divisionsOfCorpReport;
  }


  public void setDivisionsOfCorpReport(Boolean divisionsOfCorpReport) {
    this.divisionsOfCorpReport = divisionsOfCorpReport;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanComplianceInfo loanComplianceInfo = (LoanComplianceInfo) o;
    return Objects.equals(this.ofacSanctions, loanComplianceInfo.ofacSanctions) &&
        Objects.equals(this.pacerBankruptcies, loanComplianceInfo.pacerBankruptcies) &&
        Objects.equals(this.stateCourtClaims, loanComplianceInfo.stateCourtClaims) &&
        Objects.equals(this.divisionsOfCorpReport, loanComplianceInfo.divisionsOfCorpReport);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ofacSanctions, pacerBankruptcies, stateCourtClaims, divisionsOfCorpReport);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanComplianceInfo {\n");
    sb.append("    ofacSanctions: ").append(toIndentedString(ofacSanctions)).append("\n");
    sb.append("    pacerBankruptcies: ").append(toIndentedString(pacerBankruptcies)).append("\n");
    sb.append("    stateCourtClaims: ").append(toIndentedString(stateCourtClaims)).append("\n");
    sb.append("    divisionsOfCorpReport: ").append(toIndentedString(divisionsOfCorpReport)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

