/*
 * Fincura API
 * This [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) allows you to interact with the Fincura processing and insights engine.   # Authentication  This API uses API keys generated from a Fincura User account. To get access to your User account, speak with you Fincura account manager.  # Accepted Media Types  | File&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Extension(s)     | Content-Type(s) | | -------------------------------- |-------------- | ------------ | | PDF File | .pdf | `application/pdf` , `application/x-pdf` | | Excel File | .xls | `application/vnd.ms-excel`  | | Excel File | .xlsx | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`  | | Excel File | .xlsm | `application/vnd.ms-excel.sheet.macroEnabled.12`  | | PNG Image | .png | `image/png`  | | GIF Image | .gif | `image/gif`  | | JPG Image | .jpg, .jpeg | `image/jpeg`  | | GIF Image | .gif | `image/gif`  |   # Getting Started  1. [Create a Borrower](#operation/createBorrower)  2. [Add a file](#operation/createDocumentFile) for that Borrower. 3. Analyze in the Fincura App  ****
 *
 * The version of the OpenAPI document: 1.2.6
 * Contact: support@fincura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fincura.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LoanGuarantors
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-15T17:13:42.707Z[GMT]")
public class LoanGuarantors {
  public static final String SERIALIZED_NAME_FIRST_NAME = "first_name";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "last_name";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_CREDIT_SCORE = "credit_score";
  @SerializedName(SERIALIZED_NAME_CREDIT_SCORE)
  private String creditScore;

  public static final String SERIALIZED_NAME_CREDIT_SCORE_SOURCE = "credit_score_source";
  @SerializedName(SERIALIZED_NAME_CREDIT_SCORE_SOURCE)
  private String creditScoreSource;


  public LoanGuarantors firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getFirstName() {
    return firstName;
  }


  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public LoanGuarantors lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLastName() {
    return lastName;
  }


  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public LoanGuarantors creditScore(String creditScore) {
    
    this.creditScore = creditScore;
    return this;
  }

   /**
   * Get creditScore
   * @return creditScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreditScore() {
    return creditScore;
  }


  public void setCreditScore(String creditScore) {
    this.creditScore = creditScore;
  }


  public LoanGuarantors creditScoreSource(String creditScoreSource) {
    
    this.creditScoreSource = creditScoreSource;
    return this;
  }

   /**
   * Reporting agency for credit score
   * @return creditScoreSource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Reporting agency for credit score")

  public String getCreditScoreSource() {
    return creditScoreSource;
  }


  public void setCreditScoreSource(String creditScoreSource) {
    this.creditScoreSource = creditScoreSource;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanGuarantors loanGuarantors = (LoanGuarantors) o;
    return Objects.equals(this.firstName, loanGuarantors.firstName) &&
        Objects.equals(this.lastName, loanGuarantors.lastName) &&
        Objects.equals(this.creditScore, loanGuarantors.creditScore) &&
        Objects.equals(this.creditScoreSource, loanGuarantors.creditScoreSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, creditScore, creditScoreSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanGuarantors {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    creditScore: ").append(toIndentedString(creditScore)).append("\n");
    sb.append("    creditScoreSource: ").append(toIndentedString(creditScoreSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

