/*
 * Fincura API
 * This [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) allows you to interact with the Fincura processing and insights engine.   # Authentication  This API uses API keys generated from a Fincura User account. To get access to your User account, speak with you Fincura account manager.  # Accepted Media Types  | File&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Extension(s)     | Content-Type(s) | | -------------------------------- |-------------- | ------------ | | PDF File | .pdf | `application/pdf` , `application/x-pdf` | | Excel File | .xls | `application/vnd.ms-excel`  | | Excel File | .xlsx | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`  | | Excel File | .xlsm | `application/vnd.ms-excel.sheet.macroEnabled.12`  | | PNG Image | .png | `image/png`  | | GIF Image | .gif | `image/gif`  | | JPG Image | .jpg, .jpeg | `image/jpeg`  | | GIF Image | .gif | `image/gif`  |   # Getting Started  1. [Create a Borrower](#operation/createBorrower)  2. [Add a file](#operation/createDocumentFile) for that Borrower. 3. Analyze in the Fincura App  ****
 *
 * The version of the OpenAPI document: 1.2.6
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fincura.client.api;

import org.fincura.client.ApiException;
import org.fincura.client.model.DataView;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataViewsApi
 */
@Ignore
public class DataViewsApiTest {

    private final DataViewsApi api = new DataViewsApi();

    
    /**
     * Get DataView from a DocumentFile
     *
     * Retrieve a DataView from the standardized output of a DocumentFile submitted to Fincura
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveDataViewFromDocumentFileTest() throws ApiException {
        String documentFileUuid = null;
        DataView response = api.retrieveDataViewFromDocumentFile(documentFileUuid);

        // TODO: test validations
    }
    
    /**
     * Get the most recent period of data for a Borrower
     *
     * Retrieve a DataView from the most recent standardized data for a borrower
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveMostRecentDataViewTest() throws ApiException {
        String borrowerUuid = null;
        String reportingInterval = null;
        String preparationType = null;
        DataView response = api.retrieveMostRecentDataView(borrowerUuid, reportingInterval, preparationType);

        // TODO: test validations
    }
    
}
