/*
 * Fincura Integration API
 * This [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) allows you to interact with the Fincura processing and insights engine.   # Authentication  This API uses API keys generated from a Fincura User account. To get access to your User account, speak with you Fincura account manager.  # Accepted Media Types  | File&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Extension(s)     | Content-Type(s) | | -------------------------------- |-------------- | ------------ | | PDF File | .pdf | `application/pdf` , `application/x-pdf` | | Excel File | .xls | `application/vnd.ms-excel`  | | Excel File | .xlsx | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`  | | PNG Image | .png | `image/png`  | | GIF Image | .gif | `image/gif`  | | JPG Image | .jpg, .jpeg | `image/jpeg`  | | GIF Image | .gif | `image/gif`  |   # Getting Started  1. [Create a Borrower](#operation/createBorrower)  2. [Add a file](#operation/createDocumentFile) for that Borrower. 3. Analyze in the Fincura App  ****
 *
 * The version of the OpenAPI document: 1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fincura.client.api;

import org.fincura.client.ApiException;
import org.fincura.client.model.FinancialRequirement;
import org.fincura.client.model.InlineResponse2004;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RequirementsApi
 */
@Ignore
public class RequirementsApiTest {

    private final RequirementsApi api = new RequirementsApi();

    
    /**
     * Create a new FinancialRequirement
     *
     * Create a new FinancialRequirement record
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFinancialRequirementTest() throws ApiException {
        FinancialRequirement financialRequirement = null;
        FinancialRequirement response = api.createFinancialRequirement(financialRequirement);

        // TODO: test validations
    }
    
    /**
     * List FinancialRequirements
     *
     * List FinancialRequirement records
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFinancialRequirementsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String borrowerUuid = null;
        String search = null;
        InlineResponse2004 response = api.listFinancialRequirements(limit, offset, borrowerUuid, search);

        // TODO: test validations
    }
    
    /**
     * Update a FinancialRequirement
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void partialUpdateFinancialRequirementTest() throws ApiException {
        String uuid = null;
        String borrowerUuid = null;
        String search = null;
        FinancialRequirement financialRequirement = null;
        FinancialRequirement response = api.partialUpdateFinancialRequirement(uuid, borrowerUuid, search, financialRequirement);

        // TODO: test validations
    }
    
    /**
     * Retrieve a FinancialRequirement
     *
     * Retrieve a FinancialRequirement
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveFinancialRequirementTest() throws ApiException {
        String uuid = null;
        String borrowerUuid = null;
        String search = null;
        FinancialRequirement response = api.retrieveFinancialRequirement(uuid, borrowerUuid, search);

        // TODO: test validations
    }
    
}
